# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Siddharth Sharma
email: hey@siddharthsharma.io
description: null
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://siddharthsharma.io" # the base hostname & protocol for your site
linkedin_username: siddarthsharma
github_username: voixdusid
paginate: 3

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
